export const grottaFakeData = [
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
];

export const njardvikFakeData = [
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "8" },
    { name: "NAME LAST NAME", score: "10" },
    { name: "NAME LAST NAME", score: "8" },
];


export const tableFakeData = [
    {
        name: "Afturelding",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/LSMH2h1/Layer-1-2-00000077302619781270922390000014754663224647298181.png",
    },
    {
        name: "Fjölnir",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/MgtKcbN/Group.png",
    },
    {
        name: "Grindavík",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/CJ789LK/Group-1.png",
    },
    {
        name: "Grótta",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/yqNV88r/Layer-1-2-00000023987627719646506760000016023937856059140025.png",
    },
    {
        name: "ÍA",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/yRHnL7r/Group-2.png",
    },
    {
        name: "Leiknir R.",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/TW23MC7/Group-3.png",
    },
    {
        name: "Njarðvík",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/VQ8gMzk/Group-4.png",
    },
    {
        name: "Selfoss",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/zGZYkRM/Group-5.png",
    },
    {
        name: "Vestri",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/PQVtDx2/Group-6.png",
    },
    {
        name: "Vestri",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/J5GPjbT/Layer-1-2-00000016061322963425556960000007826807462006413226.png",
    },
    {
        name: "Þróttur R.",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/NrKm4TW/Group-7.png",
    },
    {
        name: "Ægir",
        l: "0",
        u: "0",
        j: "0",
        t: "0",
        m: "0 : 0",
        plusMinus: "0",
        s: "0",
        flag: "https://i.ibb.co/vhyc9bH/Group-8.png",
    },
];